### ISSUE TITLE
Permission denied when requested "--parse-only"

### ISSUE THREAD

**Issue by boozook** [jeremyfa/bind#1]
```
haxelib run bind objc ~/Developer/Projects/FooBar/BTM.h --json --parse-only --pretty
sh: ~/Developer/Haxe/libs/bind/0,2,2/cpp/Main: Permission denied
```

Same result with `sudo` 😩.

macOS: 10.12.3 (16D32)
Xcode: 8.2.1 (8C1002)
Haxe: 3.4.2 (release)
Hxcpp: 3.4.64 (release)

**Comment by boozook** [comment]
Workaround: add arg `--nodejs` founded in the source.
Or I can build cpp part: `haxe cli-cpp.hxml` from haxelib's root but :(
![screen shot 2017-03-24 at 15 10 30](https://cloud.githubusercontent.com/assets/888526/24293714/3c146ec6-10a4-11e7-8bf3-8104d34fb5d1.png)

**Comment by jeremyfa** [comment]
I actually used cpp instead of neko as a temporary workaround when running command line because at the time regexes where not working properly on neko target. This may have been solved since then. I will give a second try at neko and put it back as default if it works fine.
Until then, `--nodejs` is the most reliable workaround indeed.

Thanks for reporting!

**Comment by jeremyfa** [comment]
Now that neko doesn't have any issue with regular expressions so far, I made it default. `--nodejs` can still be used but is not needed. Removed `c++` stuff.
