### ISSUE TITLE
invalid method.

### ISSUE THREAD

**Issue by postite** [jeremyfa/bind#3]
hello ! 
i tried to use bind to generate haxe extern for sketchApp. using class-dump header (https://github.com/abynim/Sketch-Headers) which generate some method like"- (void).cxx_destruct;"   unfortunately bind log "invalid method" and stops parsing other methods...

**Comment by jeremyfa** [comment]
Hi! `bind` is not intended to parse big and too complex header files because it cannot find an equivalence for all types and signatures. It is more designed to work with a _clean_ subset of Objective-C.

Thus, best strategy is to create an Objective-C wrapper that provides a "clean" API with types interoperable with Haxe (NSString *, void, float, double, CGFloat, BOOL, ...). And call your Sketch headers from Objective-C implementation.

Also note that things are still rough and may break easily at this point. I plan to add tests and examples in the coming weeks in order to let users know how they can use `bind` utility.

**Comment by postite** [comment]
ok noté ...
merci
